<?php

declare(strict_types=1);

namespace SybaseORM\Tests\ORM;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;
use SybaseORM\Connection\ConnectionManagerInterface;
use SybaseORM\Dialect\SybaseDialect;
use SybaseORM\Metadata\ClassMetadata;
use SybaseORM\Metadata\ColumnMetadata;
use SybaseORM\Metadata\MetadataReaderInterface;
use SybaseORM\ORM\IdentityMap;
use SybaseORM\ORM\UnitOfWork;
use SybaseORM\Type\TypeCaster;

/**
 * Property-based test for Composite Key Persistence WHERE Clause Completeness.
 *
 * **Validates: Requirements 2.1, 2.2, 2.3, 2.4**
 *
 * For any entity with N primary key columns (N ≥ 1), the WHERE clause generated by the
 * UnitOfWork for UPDATE and DELETE operations SHALL contain exactly N equality conditions
 * joined with AND, one per primary key column.
 */
final class UnitOfWorkPropertyTest extends TestCase
{
    /**
     * @dataProvider randomCompositeKeyConfigurationsProvider
     *
     * @param int      $numIdColumns    Number of id columns (1–5)
     * @param string[] $idColumnNames   Database column names for id columns
     * @param int[]    $idValues        Values for each id column
     */
    public function testUpdateWhereClauseContainsExactlyNConditions(
        int $numIdColumns,
        array $idColumnNames,
        array $idValues,
    ): void {
        $executedStatements = [];
        $this->commitUpdate($numIdColumns, $idColumnNames, $idValues, $executedStatements);

        // Should have exactly one UPDATE statement
        $this->assertCount(1, $executedStatements, 'Expected exactly one UPDATE statement');

        $sql = $executedStatements[0]['sql'];
        $this->assertStringContainsString('UPDATE', $sql);

        $this->assertWhereClauseCompleteness($sql, $numIdColumns, $idColumnNames, 'UPDATE');
    }

    /**
     * @dataProvider randomCompositeKeyConfigurationsProvider
     *
     * @param int      $numIdColumns    Number of id columns (1–5)
     * @param string[] $idColumnNames   Database column names for id columns
     * @param int[]    $idValues        Values for each id column
     */
    public function testDeleteWhereClauseContainsExactlyNConditions(
        int $numIdColumns,
        array $idColumnNames,
        array $idValues,
    ): void {
        $executedStatements = [];
        $this->commitDelete($numIdColumns, $idColumnNames, $idValues, $executedStatements);

        // Should have exactly one DELETE statement
        $this->assertCount(1, $executedStatements, 'Expected exactly one DELETE statement');

        $sql = $executedStatements[0]['sql'];
        $this->assertStringContainsString('DELETE FROM', $sql);

        $this->assertWhereClauseCompleteness($sql, $numIdColumns, $idColumnNames, 'DELETE');
    }

    /**
     * Asserts that the WHERE clause in the given SQL contains exactly N equality conditions,
     * one per id column, joined with AND.
     *
     * @param string   $sql            Full SQL statement
     * @param int      $numIdColumns   Expected number of id columns
     * @param string[] $idColumnNames  Expected column names in WHERE clause
     * @param string   $operation      Operation type for error messages (UPDATE/DELETE)
     */
    private function assertWhereClauseCompleteness(
        string $sql,
        int $numIdColumns,
        array $idColumnNames,
        string $operation,
    ): void {
        // Extract the WHERE clause
        $wherePos = strpos($sql, 'WHERE');
        $this->assertNotFalse($wherePos, "{$operation} SQL must contain a WHERE clause");
        $whereClause = substr($sql, $wherePos + 6);

        // Count equality conditions (each id column produces "[col] = ?")
        $conditionCount = substr_count($whereClause, '= ?');
        $this->assertSame(
            $numIdColumns,
            $conditionCount,
            sprintf(
                '%s WHERE clause must contain exactly %d equality condition(s), got %d. SQL: %s',
                $operation,
                $numIdColumns,
                $conditionCount,
                $sql,
            ),
        );

        // Verify each id column name appears in the WHERE clause
        foreach ($idColumnNames as $colName) {
            $this->assertStringContainsString(
                '[' . $colName . ']',
                $whereClause,
                sprintf('%s WHERE clause must reference column [%s]', $operation, $colName),
            );
        }

        // For composite keys (N > 1), verify AND joins
        if ($numIdColumns > 1) {
            $andCount = substr_count($whereClause, ' AND ');
            $this->assertSame(
                $numIdColumns - 1,
                $andCount,
                sprintf(
                    '%s WHERE clause must contain exactly %d AND join(s) for %d id columns',
                    $operation,
                    $numIdColumns - 1,
                    $numIdColumns,
                ),
            );
        }
    }

    /**
     * Registers a clean entity, modifies its data column, and commits to trigger UPDATE.
     *
     * @param list<array{sql: string, params: array}> &$executedStatements
     */
    private function commitUpdate(
        int $numIdColumns,
        array $idColumnNames,
        array $idValues,
        array &$executedStatements,
    ): void {
        $entityClass = Fixtures\DynamicPropertyEntity::class;
        $idPropertyNames = $this->getIdPropertyNames($numIdColumns);

        $metadata = $this->buildMetadata($entityClass, $numIdColumns, $idPropertyNames, $idColumnNames);
        $entity = $this->buildEntity($numIdColumns, $idPropertyNames, $idValues, 'original');
        $uow = $this->buildUnitOfWork($metadata, $entityClass, $executedStatements);

        $uow->registerClean($entity);
        $entity->data = 'modified';
        $uow->commit();
    }

    /**
     * Registers a clean entity, marks it as deleted, and commits to trigger DELETE.
     *
     * @param list<array{sql: string, params: array}> &$executedStatements
     */
    private function commitDelete(
        int $numIdColumns,
        array $idColumnNames,
        array $idValues,
        array &$executedStatements,
    ): void {
        $entityClass = Fixtures\DynamicPropertyEntity::class;
        $idPropertyNames = $this->getIdPropertyNames($numIdColumns);

        $metadata = $this->buildMetadata($entityClass, $numIdColumns, $idPropertyNames, $idColumnNames);
        $entity = $this->buildEntity($numIdColumns, $idPropertyNames, $idValues, 'to_delete');
        $uow = $this->buildUnitOfWork($metadata, $entityClass, $executedStatements);

        $uow->registerClean($entity);
        $uow->registerDeleted($entity);
        $uow->commit();
    }

    /**
     * Returns fixed property names key0..keyN for the given count.
     *
     * @return string[]
     */
    private function getIdPropertyNames(int $numIdColumns): array
    {
        $names = [];
        for ($i = 0; $i < $numIdColumns; $i++) {
            $names[] = 'key' . $i;
        }
        return $names;
    }

    /**
     * Builds a ClassMetadata with the given id columns plus one non-id data column.
     */
    private function buildMetadata(
        string $entityClass,
        int $numIdColumns,
        array $idPropertyNames,
        array $idColumnNames,
    ): ClassMetadata {
        $columns = [];
        for ($i = 0; $i < $numIdColumns; $i++) {
            $columns[] = new ColumnMetadata(
                propertyName: $idPropertyNames[$i],
                columnName: $idColumnNames[$i],
                type: 'integer',
                isId: true,
            );
        }
        $columns[] = new ColumnMetadata(
            propertyName: 'data',
            columnName: 'data_col',
            type: 'string',
        );

        return new ClassMetadata(
            entityClass: $entityClass,
            tableName: 'test_table',
            columns: $columns,
            idFields: $idPropertyNames,
        );
    }

    /**
     * Creates a DynamicPropertyEntity with the given id values and data value.
     */
    private function buildEntity(
        int $numIdColumns,
        array $idPropertyNames,
        array $idValues,
        string $dataValue,
    ): Fixtures\DynamicPropertyEntity {
        $entity = new Fixtures\DynamicPropertyEntity();
        for ($i = 0; $i < $numIdColumns; $i++) {
            $entity->{$idPropertyNames[$i]} = $idValues[$i];
        }
        $entity->data = $dataValue;
        return $entity;
    }

    /**
     * Construye un UnitOfWork con dependencias mockeadas que capturan SQL ejecutado.
     *
     * @param list<array{sql: string, params: array}> &$executedStatements
     */
    private function buildUnitOfWork(
        ClassMetadata $metadata,
        string $entityClass,
        array &$executedStatements,
    ): UnitOfWork {
        /** @var ConnectionManagerInterface&MockObject $connectionManager */
        $connectionManager = $this->createMock(ConnectionManagerInterface::class);
        $connectionManager->method('executeStatement')
            ->willReturnCallback(function (string $sql, array $params = []) use (&$executedStatements): int {
                $executedStatements[] = ['sql' => $sql, 'params' => $params];
                return 1;
            });

        /** @var MetadataReaderInterface&MockObject $metadataReader */
        $metadataReader = $this->createMock(MetadataReaderInterface::class);
        $metadataReader->method('getClassMetadata')
            ->with($entityClass)
            ->willReturn($metadata);

        return new UnitOfWork(
            $connectionManager,
            $metadataReader,
            new SybaseDialect(),
            new TypeCaster(),
            new IdentityMap(),
        );
    }

    /**
     * Generates 120 random composite key configurations with 1–5 id columns.
     *
     * Each configuration provides randomized database column names and integer values,
     * while property names are fixed (key0–key4) to match the DynamicPropertyEntity fixture.
     *
     * @return \Generator<string, array{int, string[], int[]}>
     */
    public static function randomCompositeKeyConfigurationsProvider(): \Generator
    {
        for ($i = 0; $i < 120; $i++) {
            $numIdColumns = mt_rand(1, 5);
            $idColumnNames = [];
            $idValues = [];

            for ($j = 0; $j < $numIdColumns; $j++) {
                $idColumnNames[] = 'col_' . $j . '_' . mt_rand(100, 999);
                $idValues[] = mt_rand(1, 10000);
            }

            yield "iteration_{$i}_ids_{$numIdColumns}" => [
                $numIdColumns,
                $idColumnNames,
                $idValues,
            ];
        }
    }
}
